### ISSUE TITLE
Maybe actual line returns instead of `\n`?

### ISSUE THREAD

**Issue by rwxrob** [pelletier/go-toml#118]
It is really not a functional issue, but ascetically and in order to maintain the human-friendly format perhaps adding a line between the default top section and keeping the actual line returns in triple-quoted strings (""" or ''') would be easier to deal with. As it is now, the workflow of reading a TOML file, changing the data in memory, and then writing it back out again results in a file that is orders of magnitude more difficult to maintain 'by hand'. Thoughts? I can attempt a PR if you feel like it is worth it.

Before: 

![screen_shot_2016-12-04_at_12_54_46_am](https://cloud.githubusercontent.com/assets/3749067/20864420/52b16928-b9be-11e6-97b6-a2d81f5c8649.png)

After:

![screen_shot_2016-12-04_at_12_51_47_am](https://cloud.githubusercontent.com/assets/3749067/20864424/6b90a81e-b9be-11e6-81df-1fb041e43338.png)

**Comment by pelletier** [comment]
I think keeping the newlines in triple-quoted strings is a good idea. I'd be happy to see a PR for that.

As for "adding a line between the default top section", I'm not sure what you mean. In your example it seems like you're suggesting a new line between keys? If that's the case, I don't think it's a good idea, since you probably don't want newlines in e.g.

```toml
a = "foo"
b = "bar"
```

One thing that could possibly be done, is respect the `Position` of the nodes when outputting TOML. I don't think it's simple to do, but maybe would be the best fit for solving your problem of modifying documents?

**Comment by robmuh** [comment]
Yes I was noticing that in the top section there is no space between the table and the field following probably because it is having a hard time identifying between multi-line fields (like parts there) and the short single line fields as you mention.

I do think maintaining the position and distance between fields as originally intended by the author is a valid pursuit (and that it is more difficult). From my experience I find position and whitespace—not to mention comments which I didn't even test yet—is *very* important to most authors. Comments will be used to disable a field temporarily during configuration, etc.

I won't be able to look at attempting this for some time given the schedule, but please keep this ticket open if it makes sense to work on it and I will eventually try to get there (or have a student attempt it).

**Comment by pelletier** [comment]
Of course! Keeping this open as a reminder that this should be done.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released, and it seems like this issue is not in scope for v2. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1). If you believe this is a mistake please reach out!
