### ISSUE TITLE
Latest go-toml breaks Hugo

### ISSUE THREAD

**Issue by bep** [pelletier/go-toml#137]
Note, we use vendoring, so it doesn't really break Hugo.

See

https://github.com/spf13/hugo/pull/3147

A fairly simple string => toml => string roundtrip that fails at a validation step for a string key.

**Comment by pelletier** [comment]
I believe it is because you build the tree using `TreeFromMap`, which does not perform any kind of conversion – just creates the struct. `WriteTo` makes the assumption that the tree is properly constructed, which won't true in your case.

I'm working right now on rewriting `TreeFromMap` to properly build the internal representation, so that `WriteTo` (and other functions) can safely assume that the tree is well formed.

**Comment by pelletier** [comment]
https://github.com/pelletier/go-toml/pull/139 makes `TreeFromMap` return a well formed tree, so `WriteTo` will be able to work properly.

⚠️  `TreeFromMap` signature changed from `TreeFromMap(map[string]interface{}) *TomlTree` to `TreeFromMap(map[string]interface{}) (*TomlTree, error)`

**Comment by bep** [comment]
Thanks, I will pull it in and test it.

**Comment by bep** [comment]
Yes, that fixes Hugo's issue.

**Comment by pelletier** [comment]
Merged it https://github.com/pelletier/go-toml/commit/fee7787d3f811af92276f5ff10107092e95b7a1d, so closing this issue. Thanks for the feedback!
