### ISSUE TITLE
JSON to TOML tool

### ISSUE THREAD

**Issue by honkiko** [pelletier/go-toml#280]
cmd/tomljson does convert toml to json. It's also very useful to have cmd/jsontoml.

**Comment by pelletier** [comment]
Good idea! Thank you for the suggestion!

**Comment by gdhameeja** [comment]
Hey, I'd like to work on this. Please point me in the right direction.

**Comment by gdhameeja** [comment]
I wrote the code and tested it manually, it works. Will write a test and submit a PR soon.

**Comment by pelletier** [comment]
Hi! Thank you for your interest in helping out! The goal of this issue is to write another command `jsontoml`, similar to `tomljson` ([code](https://github.com/pelletier/go-toml/tree/master/cmd/tomljson)).

This program is expected to read some JSON on stdin, and emit an equivalent TOML representation on stdout.

Completion checklist:

- [ ] Unit tests
- [ ] Binary copied in the [`dockerfile`](https://github.com/pelletier/go-toml/blob/master/Dockerfile)
- [ ] Mention of the tool in the [README.md](https://github.com/pelletier/go-toml/blob/master/README.md)
- [ ] Tests execution added to [.travis.yml](https://github.com/pelletier/go-toml/blob/master/.travis.yml#L21)
- [ ] Tests execution added to [.circleci/config.yaml)(https://github.com/pelletier/go-toml/blob/master/.circleci/config.yml#L66-L68)
- [ ] Tests execution added to [appveyor.yml](https://github.com/pelletier/go-toml/blob/master/appveyor.yml#L33)

I apologize for all the changes required to the various testing services. I'm hoping to clean all that up with Github actions.

Lastly, here's a the [CONTRIBUTING.md](https://github.com/pelletier/go-toml/blob/master/CONTRIBUTING.md#code-changes) document, if you haven't seen it yet.

Let me know if anything is unclear!
