### ISSUE TITLE
Provide tree.LoadStruct() method

### ISSUE THREAD

**Issue by skyzyx** [pelletier/go-toml#350]
**Is your feature request related to a problem? Please describe.**

1. I have a nested TOML file.
1. I use `tree.Load()` to parse the TOML file.
1. I use `tree.Unmarshal()` to pass the TOML data to some Go structs which represent a JSON Schema, which represent a newer version of the data structure than what is currently inside the file. The parts of the TOML which still exist in the JSON Schema structs are now unmarshaled.
1. I use `toml.Marshal()` to output a clean version of the TOML.
1. I realize that `toml.Marshal()` has some hard-coded encoding details that I don't like (e.g., alphabetical, compact arrays).
1. For my unmarshaled data in its new format, I look for a `tree.LoadStruct()` method with which to eventually write my TOML back to disk, which does not exist.
1. After some consternation, settle on using `toml.Marshal()` to marshal the TOML back into a string, using `tree.Load()` to re-parse that TOML into a tree, then use the public `tree.WriteTo()` method to write the TOML to a file before manually reformatting it by hand.

**Describe the solution you'd like**

After using `tree.Unmarshal()` to push the data into a Go struct, allow me to re-import an instance of that struct back into a new `tree`.

**Comment by pelletier** [comment]
It sounds like the core of the issue here is that `Marshal()` does not output what you need. The intent of this method is to provide a convenient, familiar function to output TOML. If your use-case demands more control over the output format, you can use [`Encoder`](https://godoc.org/github.com/pelletier/go-toml#Encoder), which has various output settings (such as fields order and onme/multi-lines array). Would that work for you?

> For my unmarshaled data in its new format, I look for a tree.LoadStruct() method with which to eventually write my TOML back to disk, which does not exist.

`Load*` functions are to read encoded TOML (from a string, buffer, etc). To write a `Tree` back to disk, you can use [`Tree.WriteTo`](https://godoc.org/github.com/pelletier/go-toml#Tree.WriteTo). Unfortunately this method uses the same defaults as `Marshal`. If that's an issue maybe we can either tweak the `Encoder` to accept a `Tree`, provide an `Tree.Encode` method that accepts an encoder for configuration. Thoughts?
