### ISSUE TITLE
Field in the source toml data, but doesn't in the destination structure

### ISSUE THREAD

**Issue by For-ACGN** [pelletier/go-toml#367]
**Is your feature request related to a problem? Please describe.**
Not now, but may be encountered in the future.

This may happen: I set an option, I thought I configured successfully, 
but in fact did not configure successfully. I configured a timeout 
of 10s, but the result is that the timeout is always 5s due to a wrong 
field name. Similar problems may be difficult to find.

TOML data: 
``` toml
timeoutt = "10s"
```

Golang:
```go
type Dst struct {
    Timeout time.Duration `toml: "timeout"`
}
```

**Describe the solution you'd like**
I hope to add a judgment to detect whether the field is in the destination structure.
Add a option in Decoder.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by pelletier** [comment]
Interesting idea. Do you think this use case would be covered by https://github.com/pelletier/go-toml/issues/277?

**Comment by SamWhited** [comment]
I'm here while trying to update from [`https://pkg.go.dev/github.com/BurntSushi/toml`](https://pkg.go.dev/github.com/BurntSushi/toml) and found this issue and #277 but the `StrictMode` doesn't really fit my needs for two reasons:

The first is that it isn't consistently possible since it only works on decoders. I could get by parsing in strict mode, checking if there are errors, then parsing in normal mode as a hack except that I use the tree parsing which doesn't have a strict mode for unmarshaling it. The second reason is that even if I could parse twice, I can't easily get a list of keys to show that were unparsed whereas with the (now unmaintained) BurntSushi/toml that I'm upgrading from I could store the metadata and then do `metadata.Undecoded()` to get a list, which was nice.

For now I'm probably switching over to the decoder API and just reporting any errors decoding with strict mode on (then continuing with it off), but it's not ideal and makes the output (verifying a schema, more or less) not ideal.

**Comment by pelletier** [comment]
Working on this for v2: https://github.com/pelletier/go-toml/pull/512

The idea is to have a strict mode for the Decoder that does the whole parsing an returns an error containing the keys + locations of the missing fields.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released and does not have this problem. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1).
