### ISSUE TITLE
Inline table GetPosition

### ISSUE THREAD

**Issue by mkmik** [pelletier/go-toml#412]
**Describe the bug**
GetPosition (and GetPositionPath) return a position with column 0 if the tree element is inside an inline table:

**To Reproduce**
```go
	config, _ = toml.Load(`    a.b.c = {  d = "e" }`)
	fmt.Println(config.GetPosition("a.b.c.d"))
```

It prints `(1, 0)`.

Full example: https://play.golang.org/p/sOj2fK-WjLb

**Expected behavior**
The column number of the beginning of the addressed expression.
I don't honestly don't know if that should be the start of `a.b.c =...` or the start of the inner "d = .." .
But 0 seems wrong.

**Versions**
 - go-toml: v1.8.0
 - go: 1.14.3
 - operating system: macOS

**Comment by pelletier** [comment]
Good catch! `GetPosition` is supposed to return the position in the input of the given key, so for your example I would expect it to return `(1, 16)`.

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released, and it seems like this issue is not in scope for v2. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1). If you believe this is a mistake please reach out!
