### ISSUE TITLE
v2: decode - support for struct tag "default"

### ISSUE THREAD

**Issue by happyalu** [pelletier/go-toml#542]
**Describe the bug**
v1 supports the use of "default" tag on struct fields to set the default value when decoding. 
v2 seems to not support those yet. Is this likely to be added to v2? 

**To Reproduce**

```go
func main() {
	type data struct {
		Field1 string
		Field2 int `default:"9"`
	}

	var d data

	tomlBlob := []byte(`
field1 = "hello"
`)

	toml.NewDecoder(bytes.NewReader(tomlBlob)).Decode(&d)

	fmt.Printf("%+v\n", d)

	// Output with v1: {Field1:hello Field2:9}
	// Output with v2: {Field1:hello Field2:0}

}
```

**Expected behavior**
It would be great if there was either a way in v2 to set defaults.

**Versions**
 - go-toml: v1.9.1 and v2.0.0-beta.2
 - go: 1.16.4
 - operating system: Linux

**Comment by pelletier** [comment]
Thank you for bringing this up! I was thinking of removing this feature in v2 for a few reasons:

1. It does not seem like other format parsers in Go support that feature (the project referenced in the original ticket https://github.com/pelletier/go-toml/issues/202 has not been updated since 2017).
2. Given that go-toml v2 should not touch values not in the document, the same effect can be achieved by pre-filling the struct with defaults (libraries like https://github.com/mcuadros/go-defaults can help).
3. String representation is not well defined for all types. It creates issues like https://github.com/pelletier/go-toml/issues/278.

As a result, I think this feature adds complexity and a poorly defined API for an effect that can be accomplished outside of the library. I'm open to hearing arguments to keep this in though!

**Comment by happyalu** [comment]
Makes sense :) 

Prefilling the struct sounds like a good alternative. Good to know that those values won't be touched.

**Comment by pelletier** [comment]
Adding this info to the readme (https://github.com/pelletier/go-toml/pull/543). Hopefully it will clarify things for the next person. Thank you!
