### ISSUE TITLE
Single quoted keys support

### ISSUE THREAD

**Issue by pelletier** [pelletier/go-toml#61]
@robmuh provided [this example file](https://gist.github.com/robmuh/7966da29024c075349a963840e2298b2). It produces errors during parsing. They need to be fixed.

**Comment by pelletier** [comment]
@robmuh your example file contains single-quoted keys: https://gist.github.com/robmuh/7966da29024c075349a963840e2298b2#file-example-toml-L19-L20
That's the thing that makes go-toml return an error.

However, looking at the TOML 0.4.0 spec, I don't see anything mentioning this is valid syntax. The only thing I can find is

> Keys may be either bare or quoted. Bare keys may only contain letters, numbers, underscores, and dashes (A-Za-z0-9_-). Quoted keys follow the exact same rules as basic strings and allow you to use a much broader set of key names.

Which allows for `bare_keys` and `"double quoted keys"`, but not `'single quoted keys'.

**Comment by robmuh** [comment]
Unwittingly I copied blindly the examples from the main TOML page (not knowing about toml-test, which is too out of date to be useful at this point unfortunately)

<img width="920" alt="screen shot 2016-04-21 at 8 46 38 am" src="https://cloud.githubusercontent.com/assets/3749067/14709259/bc2553ca-079d-11e6-8055-82eb53b4d3d5.png">

Those look like single quoted keys to me, (even though I will never use them personally).

I believe testing the spec remains one of the biggest challenges to TOML going forward (and I would personally like to see it submitted as an IETF RFC by the end of the year if we can manage).

**Comment by pelletier** [comment]
The examples you are showing come from the latest commit on master, but not from the v0.4.0 specification.Although I'm all for trying to anticipate changes in the spec, this is not yet something that needs to be supported for the v0.4.0 compatibility.

**Comment by robmuh** [comment]
After downloading the v0.4.0 release from 2015 that Tom himself made I see what you mean:
![screen shot 2016-04-21 at 1 19 41 pm](https://cloud.githubusercontent.com/assets/3749067/14718299/df096838-07c3-11e6-99ee-77cfb250c6db.png)

Please understand my frustration since—like the rest of the world—I am going off everything that is linked to the [TOML](http://github.com/toml-lang/toml) page listing the new stuff, which we just tripped over, very clearly at v0.4.0. 

I won't lie. I pretty upset by all the hours I have lost on this fiasco, (which isn't any one persons fault I imagine), enough to manage my own spec and forked versions of the main implementations since I have such critical demand for this stuff. Several projects are suffering because of the lack of a a spec and the internet is full of blogs about TOML being overlooked because of it's lack of 1.0-ness. People are using YAML *gag* instead, lol.</rant>

For what it's worth I have a start at the [examples](http://github.com/toml-spec/tests-v0.4.0) I will be using from now on. Obviously we'll have to figure out what to call that version because it IS NOT v0.4.0 as tagged by the original project maintainers.

**Comment by robmuh** [comment]
I've opened this [bug](https://github.com/toml-lang/toml/issues/407) on it with the toml-lang folk.

**Comment by pelletier** [comment]
Let's implement that anyway. That is not a backward compatible change so there's no harm in doing that.

**Comment by kzys** [comment]
Sorry. My change was not enough. I should have edited lexKey() to handle single quotes.

Also parseKey()'s input is not clear because;
- lexKey() sends a string without escape sequences, because lexStringAsString() processes all escape sequences
- lexInsideTableKey() and lexInsideTableArrayKey() send a string with unprocessed escape sequences
- Tree#Get()'s input would have escape sequences

Due to that, my change is unnecessary (or have undesirable effect) on lexKey(), but would be needed for the rest of them.

**Comment by kzys** [comment]
We may be possible to use multiple `tokenKey` tokens instead of `tokenKeyGroupArray` and `tokenKeyGroup`.

**Comment by pelletier** [comment]
@kzys good catch, I completely missed that. Are you working on it or do you want me to create an issue to track that?

**Comment by kzys** [comment]
I opened a new pull request to address the issue.
