### ISSUE TITLE
Yacc Consideration?

### ISSUE THREAD

**Issue by robmuh** [pelletier/go-toml#68]
Just wondering if you have ever looked into `yacc` for parsing. Eventually if TOML gets a formal specification YACC would be a great way to represent the exact syntax of the TOML language. Tempted to play with it.

**Comment by pelletier** [comment]
At the very beginning, go-toml was a personal project to learn Go and implementing a lexer/parser using the method described by Rob Pike in one of his talk. I'm increasingly thinking about implementing go-toml by generating a PEG parser. I'm however not happy with the Go implementations I have found so far, so it would require rolling our own. If that turns out to be too much of a daunting task, cmd/yacc will probably be used as an alternative.

**Comment by pelletier** [comment]
@robmuh closing this. If you ever find the time and interest to write a POC for yacc (or any parser generator that would fit the bill), I'd be happy to check it out!
