### ISSUE TITLE
GetPosition key with inline table

### ISSUE THREAD

**Issue by Atilogit** [pelletier/go-toml#697]
**Describe the bug**
GetPosition returns `(0, 0)` for key with inline table.

**To Reproduce**
```go
config, _ := toml.Load(`
[A]
B = { id = 1 }
`)
fmt.Println(config.GetPosition("A.B"))
```
Output: `(0, 0)`

Playground: https://go.dev/play/p/jZd_WK4pl0W

**Expected behavior**
`config.GetPosition("A.B")` should return something like `(3, 1)`. Instead it returns `(0, 0)`

**Versions**
 - go-toml: v1.9.4
 - go: 1.17.2
 - operating system: Windows

**Comment by pelletier** [comment]
Thanks for the report! My focus for go-toml is on getting v2.0.0 over the finish line (which does not have a document model), but I am happy to take a pull request for it!

**Comment by pelletier** [comment]
Closing this issue, as [go-toml v2.0.0](https://github.com/pelletier/go-toml/releases/tag/v2.0.0) has been released, and it seems like this issue is not in scope for v2. As go-toml v1 will not be receiving any updates, please look into [upgrading to the new version](https://github.com/pelletier/go-toml/#migrating-from-v1). If you believe this is a mistake please reach out!
