### ISSUE TITLE
Panic when value is missing

### ISSUE THREAD

**Issue by TomWright** [pelletier/go-toml#732]
**Describe the bug**
I received a bug report on my project and it seems to be an upstream issue from this project.

https://github.com/TomWright/dasel/issues/191

**To Reproduce**
Parsing the given toml will panic.
```toml
[test]
something =
foo = "bar"
```

**Expected behavior**
A clear and concise description of what you expected to happen, if other than "should work".

**Versions**
 - go-toml: v1.9.3
 - go: 1.17
 - operating system: Host: ultima-jd-pc Kernel: 5.10.79-1-MANJARO x86_64 bits: 64 Desktop: GNOME 41.1 Distro: Manjaro Linux

**Comment by pelletier** [comment]
Should be fixed by https://github.com/pelletier/go-toml/commit/fed1464066413075eac02cd4dc368b5221845541 from @moorereason.

After a quick look to https://github.com/TomWright/dasel it seems like you're only using `toml.Unmarshal` and `toml.Encoder`. If you're keen I'd encourage you to try out `go-toml/v2`: https://github.com/pelletier/go-toml/tree/v2. It's faster, less buggy, and should be released to stable soon.

**Comment by TomWright** [comment]
Thanks for the quick fix!

I'd be happy to upgrade to v2 as soon as it's stable 🙂

**Comment by pelletier** [comment]
@TomWright go-toml v2.0.0 has been released!  – https://github.com/pelletier/go-toml/releases/tag/v2.0.0

**Comment by TomWright** [comment]
Thank you very much 😁
