### ISSUE TITLE
v2.0.0-beta.6 checksum mismatch

### ISSUE THREAD

**Issue by chenguowei** [pelletier/go-toml#743]
verifying github.com/pelletier/go-toml/v2@v2.0.0-beta.6: checksum mismatch
        downloaded: h1:TA3qh4Cq1VOjh4AJnMHrUFbAsIbD7OnOvpaIRYsU0sI=
        go.sum:     h1:JFNqj2afbbhCqTiyN16D7Tudc/aaDzE2FBDk+VlBQnE=

**Comment by pelletier** [comment]
I have pushed the `v2.0.0-beta.6` release on github: https://github.com/pelletier/go-toml/releases/tag/v2.0.0-beta.6

However I doubt this fixes the checksum mismatch issue, which is likely caused by the tag having moved.

I will be release `v2.0.0-beta.7` to fix this problem as soon as I'm done with those [two bugs](https://github.com/pelletier/go-toml/milestone/14).

**Comment by pelletier** [comment]
Pushed [2.0.0-beta.7](https://github.com/pelletier/go-toml/releases/tag/v2.0.0-beta.7), which should be a clean build. Let me know if you're still facing any issue!
