### ISSUE TITLE
String() fails on map[string]string

### ISSUE THREAD

**Issue by bep** [pelletier/go-toml#99]
```go
package main

import (
	"fmt"

	toml "github.com/pelletier/go-toml"
)

func main() {
	m1 := map[string]string{"v": "abc"}
	m2 := map[string]interface{}{"m": m1}
	tree := toml.TreeFromMap(m2)
	fmt.Println(tree.String())
}
```

Panics:

```
panic: unsupported value type: map[v:abc]
```

In Hugo we do frontmatter conversions between YAML and TOML etc., and the datatypes for maps differs slightly. We recently converted from Burntsushi to pelletier's go-toml for Hugo and related libraries. We are in the process to release a new version of Hugo and need to fix this in a way or another.

See https://github.com/spf13/hugo/issues/2439

**Comment by pelletier** [comment]
`TreeFromMap` is not supposed to be used with anything else than an already converted tree, as it's just a constructor for `TomlTree`. This is unfortunate, as this function should not have existed as a first place, yet being public.

As for your issue, the problem is the `map[string]string` is not a supported node in a `TomlTree`. I think the best way to handle that is to write a function that walks your input configuration object and performs the corresponding `SetPath` operations to reconstruct the TomlTree.

**Comment by bep** [comment]
Not sure if you expect *me* to write this new func on my side to handle this. I have spent too much time on this already, and I suspect the move to a new TOML library was a little bit premature, driven by some licensing issues in the Kubernetes project.

* There is nothing in the `TreeFromMap` doc that suggests the mentioned problems.
* I suggest you deprecate `TreeFromMap` and at some time unexport it.
* Add a new `NewAndBetterTreeFromMap` that does a better job at handling common data types.

**Comment by moorereason** [comment]
Instead of `NewAndBetterTreeFromMap`, let's go with `Marshal`.  :smile:

```go
func Marshal(v interface{}) ([]byte, error) {
```

**Comment by bep** [comment]
On second thought I now notice we have a similar situation when going from YAML to JSON:

```
Error: json: unsupported type: map[interface {}]interface {}
```

Hmm ... Maybe be should add an adapter or similar.

**Comment by moorereason** [comment]
I still think `toml.Marshal` is the way to go.
